export const ADD_TODO = 'ADD_TODO'
export const INIT_TODOS = 'INIT_TODOS'
export const UPDATE_TODOS = 'UPDATE_TODOS'
export const TO_EDITING = 'TO_EDITING'
export const ADD_TOMATO = 'ADD_TOMATO'
export const INIT_TOMATOES = 'INIT_TOMATOES'
